'''
Created on Mar 23, 2013

@author: rahul
'''

SEARCH_RESULTS_LIMIT = 1000
NUMBER_OF_COLUMNS_IN_UI_FOR_EMAILS = 10
CHAR_LIMIT_IN_RESULTS_TAB_CELLS = 80
SHELVE_CHUNK_SIZE = 100;
SHELVE_FILE_EXTENSION = ".shelve"

COLUMN_NUMBER_OF_RATING = 3